notifications:
  email: false
language: python
python:
  - "2.7"
  - "3.4"
#  - "3.5.0b3"
#  - "3.5-dev"
#  - "nightly"

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - pip install coveralls

# command to run tests
script:
  - "python test/PostgresNoSQLClientTest.py"
  - "python test/PostgresNoSQLDatabaseTest.py"
  - "python test/PostgresNoSQLTableTest.py"

after_success:
  - coveralls